WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/ProductModel.cs
namespace WebApplication1.Models
{
        public record class ProductModel(int ID, string name, float Price); 
}

WebApplication1/Models/WeatherMapModel.cs
namespace WebApplication1.Models
{
    public class Coord
    {
        public double lon { get; set; }
        public double lat { get; set; }
    }
    public class Weather
    {
        public int id { get; set; }
        public string main { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
    }
    public class Main
    {
        public double temp { get; set; }
        public int pressure { get; set; }
        public int humidity { get; set; }
        public float temp_min { get; set; }
        public float temp_max { get; set; }
    }
    public class Wind
    {
        public double speed { get; set; }
        public int deg { get; set; }
    }
    public class Clouds
    {
        public int all { get; set; }
    }
    public class Sys
    {
        public int type { get; set; }
        public int id { get; set; }
        public double message { get; set; }
        public string country { get; set; }
        public int sunrise { get; set; }
        public int sunset { get; set; }
    }
    public class ResponseWeather
    {
        public Coord coord { get; set; }
        public List<Weather> weather { get; set; }
        public string @base { get; set; }
        public Main main { get; set; }
        public int visibility { get; set; }
        public Wind wind { get; set; }
        public Clouds clouds { get; set; }
        public int dt { get; set; }
        public Sys sys { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int cod { get; set; }
    }
}

WebApplication1/Components/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Components
{
    public class ProductListViewComponent : ViewComponent
    {
        List<ProductModel> productList = new List<ProductModel>
        {
            new ProductModel(1, "Випарник Smok RPM 3", 125),
            new ProductModel(2, "Картридж Smok Nord 4", 99),
            new ProductModel(3, "Картридж Smok RPM", 130),
            new ProductModel(4, "Випарник Smok RPM 2", 120)
        };
        public IViewComponentResult Invoke()
        {
            return View(productList);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Home/Components/ProductList/Default.cshtml
@model IEnumerable<WebApplication1.Models.ProductModel>
<style>
    td{
        padding-right: 10px;
        border: 2px solid;
        text-align: center;
    }
    th{
        border: 2px solid;
        padding-left: 5px;
        padding-right: 5px;
    }
</style>
<h1>Product List</h1>
<table>
    @foreach(var product in Model)
    {
    <tr>
        <th>@product.ID</th>
        <td>@product.name</td>
        <td>@product.Price</td>
    </tr>
    }
</table>

WebApplication1/Views/Home/Components/WeatherMap/Default.cshtml
@model WebApplication1.Models.ResponseWeather
<h1>Погода в @(Model.name)</h1>
<div>
    <div>
        <span>Температура: @(Model.main.temp + " `C")</span>
    </div>
    <div>
        <span>Город: @(Model.name)</span>
    </div>
    <div>
        <span><img src=@("https://openweathermap.org/img/w/" + Model.weather[0].icon + ".png") /></span>
        <span>@(Model.weather[0].description)</span>
    </div>
    <div>
        <span>Максимальна температура: @(Model.main.temp_max + "`C")</span>
    </div>
    <div>
        <span>Мінімальна температура: @(Model.main.temp_min + "`C")</span>
    </div>
    <div>
        <span>Швидкість вітру: @(Model.wind.speed + " км/г")</span>
    </div>
    <div>
        <span>Тиск: @(Model.main.pressure + " Н/м²")</span>
    </div>
    <div>
        <span>lon: @(Model.coord.lon)</span>
        <span>lat: @(Model.coord.lat)</span>
    </div>
</div>

WebApplication1/Views/Home/Index.cshtml
@{
    var city = "Mykolaiv";
}

<div class="container">
    <div class="row">
        <div class="col-6">
            @await Component.InvokeAsync("ProductList")
        </div>
        <div class="col-6">
            @await Component.InvokeAsync("WeatherMap", city)
        </div>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>